### ISSUE TITLE
/binlogfile2sql.py 怎么使用能举例一下吗？用这个可以离线解析binlog吗

### ISSUE THREAD

**Issue by lizhiyou88** [michael-liumh/binlog2sql#2]
binlogfile2sql.py 怎么使用能举例一下吗？用这个可以离线解析binlog吗

**Comment by michael-liumh** [comment]
1. 怎么用
python3 binlogfile2sql.py --help
可以查看所有的参数


2. 可以离线吗？
不完全支持离线，只是不要求binlog文件存在于```show master logs;```中，但还是需要连接到实例去获取表的元数据信息的。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月19日(周三) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [michael-liumh/binlog2sql] /binlogfile2sql.py 怎么使用能举例一下吗？用这个可以离线解析binlog吗 (Issue #2)




 
binlogfile2sql.py 怎么使用能举例一下吗？用这个可以离线解析binlog吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
