### ISSUE TITLE
编码问题使用 binlogfile2sql.py 不能解析binlog

### ISSUE THREAD

**Issue by lizhiyou88** [michael-liumh/binlog2sql#3]
Traceback (most recent call last):
  File "/root/binlog2sql/binlogfile2sql.py", line 248, in <module>
    main(command_line_args)
  File "/root/binlog2sql/binlogfile2sql.py", line 216, in main
    bin2sql.process_binlog()
  File "/root/binlog2sql/binlogfile2sql.py", line 96, in process_binlog
    for binlog_event in stream:
  File "/root/binlog2sql/binlogfile2sql_util.py", line 197, in fetchone
    self.__fail_on_table_metadata_unavailable)
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/packet.py", line 139, in __init__
    fail_on_table_metadata_unavailable=fail_on_table_metadata_unavailable)
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/row_event.py", line 587, in __init__
    self.column_schemas = self._ctl_connection._get_table_information(self.schema, self.table)
  File "/root/binlog2sql/binlogfile2sql_util.py", line 324, in __get_table_information
    cur.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1347, in read
    self._read_result_packet(first_packet)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1413, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1451, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1467, in _read_row_from_packet
    data = data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 13: invalid continuation byte

**Comment by michael-liumh** [comment]
请确认一下数据库的字符集配置是否为 utf8 或 utf8mb4

**Comment by JasonRinnki** [comment]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 133: invalid continuation byte
数据库的字符集已经配置为utf8mb4了，但是还是报上面这个错误，还需要注意什么地方？
mysql> show variables like 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_general_ci |
| collation_database   | utf8mb4_general_ci |
| collation_server     | utf8mb4_general_ci |
+----------------------+--------------------+
3 rows in set (0.01 sec)

mysql> show variables like '%character%';
+--------------------------+-----------------------------------+
| Variable_name            | Value                             |
+--------------------------+-----------------------------------+
| character_set_client     | utf8mb4                           |
| character_set_connection | utf8mb4                           |
| character_set_database   | utf8mb4                           |
| character_set_filesystem | binary                            |
| character_set_results    | utf8mb4                           |
| character_set_server     | utf8mb4                           |
| character_set_system     | utf8mb3                           |
| character_sets_dir       | /usr/local/mysql8/share/charsets/ |
+--------------------------+-----------------------------------+
8 rows in set (0.00 sec)

**Comment by michael-liumh** [comment]
你要看你这张表的每个字段是不是都用 utf8 存储的，全局那个只是默认选项，如果表有自定义的话，还是以表的为准的
如果你存的是二进制数据，那你用utf8解码不出来，那也很正常
如果表结构都是utf8的话，那可能是bug，或者原表里本身存储的数据就是有问题的，你可以尝试改一下代码，看这个错误输出之前，数据库里存的数据是什么样的，或者单独把这行数据的主键打印出来，然后用这个主键去原表里确认一下数据是否正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [michael-liumh/binlog2sql] 编码问题使用 binlogfile2sql.py 不能解析binlog (Issue #3)




 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 133: invalid continuation byte
 数据库的字符集已经配置为utf8mb4了，但是还是报上面这个错误，还需要注意什么地方？
 mysql&gt; show variables like 'collation%';
 +----------------------+--------------------+
 | Variable_name        | Value              |
 +----------------------+--------------------+
 | collation_connection | utf8mb4_general_ci |
 | collation_database   | utf8mb4_general_ci |
 | collation_server     | utf8mb4_general_ci |
 +----------------------+--------------------+
 3 rows in set (0.01 sec)
 
mysql&gt; show variables like '%character%';
 +--------------------------+-----------------------------------+
 | Variable_name            | Value                             |
 +--------------------------+-----------------------------------+
 | character_set_client     | utf8mb4                           |
 | character_set_connection | utf8mb4                           |
 | character_set_database   | utf8mb4                           |
 | character_set_filesystem | binary                            |
 | character_set_results    | utf8mb4                           |
 | character_set_server     | utf8mb4                           |
 | character_set_system     | utf8mb3                           |
 | character_sets_dir       | /usr/local/mysql8/share/charsets/ |
 +--------------------------+-----------------------------------+
 8 rows in set (0.00 sec)

**Comment by JasonRinnki** [comment]
我尝试用mysqlbinlog解出日志，查询到有些记录字段值采用了utf8编码（是和这个有关系吗），
如果这样的话，如何忽略这一错误？修改那个文件的代码实现忽略

**Comment by michael-liumh** [comment]
跟这个没关



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [michael-liumh/binlog2sql] 编码问题使用 binlogfile2sql.py 不能解析binlog (Issue #3)




 
我尝试用mysqlbinlog解出日志，查询到有些记录字段值采用了utf8编码（是和这个有关系吗），
 如果这样的话，如何忽略这一错误？修改那个文件的代码实现忽略
